spring:
  application:
    name: chatAI
  ai:
    deepseek:
      api-key: sk-22c8e95eaad84ff6b1ffe60b9e48d84e
    ollama:
      base-url: http://localhost:11434 # ollama server url
      chat:
        options:
          model: deepseek-r1:8b